import { Schema, model } from 'mongoose'

const laptopSchema = Schema(
    {
        img: { type: String },
        price: { type: Number },
        brand_name: { type: String },
        laptop_name: { type: String },
        sales_package: { type: String },
        model_number: { type: String },
        part_number: { type: String },
        model_name: { type: String },
        color: { type: String },
        type: { type: String },
        suitable_for: { type: String },
        battery_cell: { type: String },
        ms_office_provided: { type: String },
        processor_brand: { type: String },
        processor_name: { type: String },
        cache: { type: String },
        processor_generation: { type: String },
        ssd: { type: String },
        ssd_capacity: { type: String },
        ram: { type: String },
        ram_type: { type: String },
        ram_frequency: { type: String },
        processor_variant: { type: String },
        cpu_score: { type: Number, default: 0 },
        memory_score: { type: Number, default: 0 },
        storage_score: { type: Number, default: 0 },
        connectivity_score: {type: Number, default: 0},
        total_score: { type: Number, default: 0 },
        clock_speed: { type: String },
        graphic_processor: { type: String },
        number_of_cores: { type: String },
        os_architecture: { type: String },
        operating_system: { type: String },
        supported_operating_system: { type: String },
        usb_port: { type: String },
        hdmi_port: { type: String },
        multi_card_slot: { type: String },
        touchscreen: { type: String },
        screen_size: { type: String },
        screen_resolution: { type: String },
        screen_type: { type: String },
        speakers: { type: String },
        internal_mic: { type: String },
        wireless_lan: { type: String },
        bluetooth: { type: String },
        ethernet: { type: String },
        dimensions: { type: String },
        weight: { type: String },
        disk_drive: { type: String },
        web_camera: { type: String },
        finger_print_sensor: { type: String },
        keyboard: { type: String },
        backlit_keyboard: { type: String },
        pointer_device: { type: String },
        included_software: { type: String },
        warranty_summary: { type: String },
        warranty_service_type: { type: String },
        covered_in_warranty: { type: String },
        not_covered_in_warranty: { type: String },
        domestic_warranty: { type: String },
    },
    { timestamps: true }
)

const Laptop = model('laptop', laptopSchema)

export default Laptop
