import { Schema, model } from 'mongoose'

const laptopSchema = Schema(
    {
        img: { type: String },
        price: { type: Number },
        brandName: { type: String },
        laptopName: { type: String },
        salesPackage: { type: String },
        modelNumber: { type: String },
        partNumber: { type: String },
        modelName: { type: String },
        color: { type: String },
        type: { type: String },
        suitable_for: { type: String },
        batteryCell: { type: String },
        msOfficeProvided: { type: String },
        processorBrand: { type: String },
        processorName: { type: String },
        cache: { type: String },
        processorGeneration: { type: String },
        ssd: { type: String },
        ssdCapacity: { type: String },
        ram: { type: String },
        ramType: { type: String },
        ramFrequency: { type: String },
        processorVariant: { type: String },
        cpuScore: { type: Number, default: 0 },
        memoryScore: { type: Number, default: 0 },
        storageScore: { type: Number, default: 0 },
        graphicsScore: { type: Number, default: 0 },
        connectivityScore: { type: Number, default: 0 },
        multimediaScore: { type: Number, default: 0 },
        totalScore: { type: Number, default: 0 },
        clockSpeed: { type: String },
        graphicProcessor: { type: String },
        numberOfCores: { type: String },
        osArchitecture: { type: String },
        operatingSystem: { type: String },
        supportedOperatingSystem: { type: String },
        usbPort: { type: String },
        hdmiPort: { type: String },
        multiCardSlot: { type: String },
        touchscreen: { type: String },
        screenSize: { type: String },
        screenResolution: { type: String },
        screenType: { type: String },
        speakers: { type: String },
        internalMic: { type: String },
        wirelessLan: { type: String },
        bluetooth: { type: String },
        ethernet: { type: String },
        dimensions: { type: String },
        weight: { type: String },
        diskDrive: { type: String },
        webCamera: { type: String },
        fingerPrintSensor: { type: String },
        keyboard: { type: String },
        backlitKeyboard: { type: String },
        pointerDevice: { type: String },
        includedSoftware: { type: String },
        warrantySummary: { type: String },
        warrantyServiceType: { type: String },
        coveredInWarranty: { type: String },
        notCoveredInWarranty: { type: String },
        domesticWarranty: { type: String },
    },
    { timestamps: true }
)

const Laptop = model('laptop', laptopSchema)

export default Laptop
