import { Router } from "express";
import cache from "../../helper/express_cache";
import bulkInsert from "./addBulkLaptops";
import deleteLaptop from "./deleteLaptop";
import getDuplicates from "./fetchDuplicates";
import filterBySpec from "./filterBySpec";
import filterByPrice from "./filterLaptopByPrice";
import getAllLaptops from "./getLaptops";
import fetchSingleLaptop from "./getSingleLaptop";
import updateLaptop from "./updateLaptop";
import updatePricing from "./updatePricing";
import laptopValidate from "./validations";
const lapRouter = Router();

lapRouter.delete("/:laptopID", deleteLaptop);
lapRouter.post("/:laptopID", /* laptopValidate ,*/ updateLaptop);
lapRouter.get("/",  getAllLaptops);
lapRouter.get("/single/:laptopID", fetchSingleLaptop);
lapRouter.get("/pricing", updatePricing);
lapRouter.get("/duplicate", getDuplicates);
lapRouter.get("/bulk", bulkInsert);
lapRouter.get("/search", filterByPrice);
lapRouter.get("/filter",  filterBySpec);
export default lapRouter;
